#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get install -y --allow-downgrades nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
